const bhajansUrls = [
  '/bhajans/adisesha-anantha-sayana-bhajana',
  '/bhajans/digu-digu-digu-naga-naga-bhajan-telugu-lyrics',
  '/bhajans/shabari-kondapai-velasina-ayyappa',
  '/bhajans/swagatham-suswagatham-telugu-ayyappa-bhajan',
  '/bhajans/thandhane-thandhane-telugu-ayyappa-swamy-and-shanmukha-swamy-bhajan',
  '/bhajans/annadana-prabhuve-telugu-ayyappa-devotional-bhajan-song',
  '/bhajans/pratiroju-nee-namame-telugu-ayyappa-bhajan',
  '/bhajans/swamiye-sharanam-ayyappa-swamy-telugu-devotional-bhajan',
  '/bhajans/villali-veerane-ayyappa-swamy-bhajan',
  '/bhajans/aatma-nischalamaithe-telugu-devotional-bhajan',
  '/bhajans/lingashtakam-lord-shiva-swami-ayyappa-bhajan-song',
  '/bhajans/vandanalu-vandanalu-bhajan',
  '/bhajans/kukkuta-dhwaja-ayyappa-bhajan',
  '/bhajans/uyyaala-paata-swami-ayyappa-lullaby-bhajan',
  '/bhajans/satyamu-jyothiga-ayyappa-swamy-mahima-bhajan-song',
  '/bhajans/dimi-dimi-dimitaka-swami-ayyappa-dance-bhajan',
  '/bhajans/navapata-ayyappa-bhajan-song',
  '/bhajans/adigadigo-shabari-mala-swami-ayyappa-yatra-bhajan',
  '/bhajans/ambarameshwari-devi-bhajan',
  '/bhajans/kondallo-koluvunna-kondadevara-swami-ayyappa-bhajan',
  '/bhajans/dandalamma-malikappuram-amma-bhajan',
  '/bhajans/ennenni-namalayyo-swami-ayyappa-bhajan',
  '/bhajans/bhagavan-sharanam-bhagavati-sharanam',
  '/bhajans/manoharam-swami-ayyappa-bhajan',
  '/bhajans/rama-rama-antu-devotional-bhajan',
  '/bhajans/velvele-velayya-subramanya-swamy-bhajan',
  '/bhajans/ganesha-paata-ganapati-bhajan',
  '/bhajans/saranam-ganesha-ganapati-bhajan',
];

export default bhajansUrls;
