const bhakthiSongsUrls = [
  '/bhakthi-songs/mahishasura-mardini-stotram',
  '/bhakthi-songs/bilvashtakam',
  '/bhakthi-songs/gaganalo-ayyappa-bhakti-song',
  '/bhakthi-songs/ayya-darshanam-ayyappa-bhakti-song',
  '/bhakthi-songs/namadi-swarnalayam-ayyappa-bhakti-song',
  '/bhakthi-songs/anta-dukhhamu-ayyappa-bhakti-song',
  '/bhakthi-songs/swami-saranam-ayyappa-bhakti-song',
  '/bhakthi-songs/durgamupaina-kanaka-durga-vai-kanaka-durga-bhakti-song',
  '/bhakthi-songs/chetuletti-ayyappa-bhakti-song',
  '/bhakthi-songs/makara-deepamaa-ayyappa-bhakti-song',
  '/bhakthi-songs/kanivini-erugani-ghanayogam-ayyappa-bhakti-song',
  '/bhakthi-songs/prati-bhaktuni-hrudayam-ayyappa-bhakti-song',
  '/bhakthi-songs/bhoota-gana-naadha-ayyappa-bhakti-song',
  '/bhakthi-songs/saranam-nee-charanam-ayyappa-bhakti-song',
  '/bhakthi-songs/eeshwara-nilayam-ayyappa-bhakti-song',
  '/bhakthi-songs/dhanyoham-o-shabarisha-ayyappa-bhakti-song',
  '/bhakthi-songs/om-om-ayyappa-ayyappa-bhakti-song',
  '/bhakthi-songs/aakashamanti-ayyappa-bhakti-song',
  '/bhakthi-songs/karthika-masamu-ayyappa-bhakti-song',
  '/bhakthi-songs/makara-deepam-ayyappa-bhakti-song',
  '/bhakthi-songs/oke-oka-lakshyam-ayyappa-bhakti-song',
  '/bhakthi-songs/swami-geethale-ayyappa-bhakti-song',
  '/bhakthi-songs/mala-dharanam-ayyappa-bhakti-song',
];

export default bhakthiSongsUrls;
