const sahasranamavaliUrls = [
  '/sahasranamavali/sri-varaha-sahasranamavali',
  '/sahasranamavali/sri-sarasvati-sahasranamavali',
  '/sahasranamavali/sri-matangi-sahasranamavali',
  '/sahasranamavali/sri-shyamala-sahasranamavali',
  '/sahasranamavali/sri-shirdi-sai-sahasranamavali',
  '/sahasranamavali/sri-sai-sahasranamavali',
  '/sahasranamavali/sri-dattatreya-sahasranamavali',
  '/sahasranamavali/sri-hanuman-sahasranamavali',
  '/sahasranamavali/sri-subrahmanya-sahasranamavali-2',
  '/sahasranamavali/sri-krishna-sahasranamavali',
  '/sahasranamavali/sri-pratyangira-sahasranamavali',
  '/sahasranamavali/sri-vishnu-sahasranamavali',
  '/sahasranamavali/sri-kalabhairava-sahasranamavali',
  '/sahasranamavali/sri-sita-devi-sahasranamavali',
  '/sahasranamavali/sri-vasavi-sahasranamavali',
  '/sahasranamavali/sri-dharmashastra-sahasranamavali',
  '/sahasranamavali/sri-kali-sahasranamavali',
  '/sahasranamavali/sri-ganapati-sahasranamavali',
  '/sahasranamavali/sri-tulasi-sahasranamavali',
  '/sahasranamavali/sri-gayatri-sahasranamavali',
  '/sahasranamavali/sri-lalitha-devi-sahasranamavali',
  '/sahasranamavali/sri-venkateswara-sahasranamavali',
  '/sahasranamavali/sri-rama-sahasranamavali',
  '/sahasranamavali/sri-shani-sahasranamavali',
  '/sahasranamavali/sri-surya-sahasranamavali',
  '/sahasranamavali/sri-saraswathi-sahasranamavali',
  '/sahasranamavali/sri-lakshmi-sahasranamavali',
  '/sahasranamavali/sri-subrahmanya-sahasranamavali',
  '/sahasranamavali/sri-shiva-sahasranamavali',
  '/sahasranamavali/sri-varahi-devi-sahasranamavali',
];

export default sahasranamavaliUrls;
