export const FESTIVALS = [
  {
    name: 'Bhogi',
    name_te: 'భోగి',
    path: '/calendar/festivals/bhogi',
    image: '/images/festivals/bhogi.png',
    image_te: '/images/festivals/bhogi_te.png',
  },
  {
    name: 'Makara Sankranti',
    name_te: 'మకర సంక్రాంతి',
    path: '/calendar/festivals/makara-sankranthi',
    image: '/images/festivals/makara-sankranthi.png',
    image_te: '/images/festivals/makara-sankranthi_te.png',
  },
  {
    name: 'Kanuma',
    name_te: 'కనుమ',
    path: '/calendar/festivals/kanuma',
    image: '/images/festivals/kanuma.png',
    image_te: '/images/festivals/kanuma_te.png',
  },
  {
    name: 'Ratha Saptami',
    name_te: 'రథ సప్తమి',
    path: '/calendar/festivals/ratha-saptami',
    image: '/images/festivals/ratha-saptami.png',
    image_te: '/images/festivals/ratha-saptami_te.png',
  },
  {
    name: 'Maha Shivaratri',
    name_te: 'మహా శివరాత్రి',
    path: '/calendar/festivals/maha-shivaratri',
    image: '/images/festivals/maha-shivaratri.png',
    image_te: '/images/festivals/maha-shivaratri_te.png',
  },
  {
    name: 'Holi',
    name_te: 'హోళీ',
    path: '/calendar/festivals/holi',
    image: '/images/festivals/holi.png',
    image_te: '/images/festivals/holi_te.png',
  },
  {
    name: 'Ugadi',
    name_te: 'ఉగాది',
    path: '/calendar/festivals/ugadi',
    image: '/images/festivals/ugadi.png',
    image_te: '/images/festivals/ugadi_te.png',
  },
  {
    name: 'Rama Navami',
    name_te: 'శ్రీరామ నవమి',
    path: '/calendar/festivals/rama-navami',
    image: '/images/festivals/rama-navami.png',
    image_te: '/images/festivals/rama-navami_te.png',
  },
  {
    name: 'Hanuman Jayanti',
    name_te: 'హనుమాన్ జయంతి',
    path: '/calendar/festivals/hanuman-jayanti',
    image: '/images/festivals/hanuman-jayanti.png',
    image_te: '/images/festivals/hanuman-jayanti_te.png',
  },
  {
    name: 'Vinayaka Chaturthi',
    name_te: 'వినాయక చవితి',
    path: '/calendar/festivals/vinayaka-chaturthi',
    image: '/images/festivals/vinayaka-chaturthi.png',
    image_te: '/images/festivals/vinayaka-chaturthi_te.png',
  },
  {
    name: 'Krishna Janmashtami',
    name_te: 'కృష్ణ జన్మాష్టమి',
    path: '/calendar/festivals/janmashtami',
    image: '/images/festivals/janmashtami.png',
    image_te: '/images/festivals/janmashtami_te.png',
  },
  {
    name: 'Vijayadashami',
    name_te: 'దసరా',
    path: '/calendar/festivals/vijayadashami',
    image: '/images/festivals/vijayadashami.png',
    image_te: '/images/festivals/vijayadashami_te.png',
  },
  {
    name: 'Diwali',
    name_te: 'దీపావళి',
    path: '/calendar/festivals/diwali',
    image: '/images/festivals/diwali.png',
    image_te: '/images/festivals/diwali_te.png',
  },
  {
    name: 'Karthika Pournami',
    name_te: 'కార్తీక పౌర్ణమి',
    path: '/calendar/festivals/karthika-pournami',
    image: '/images/festivals/karthika-pournami.png',
    image_te: '/images/festivals/karthika-pournami_te.png',
  },
];
