export class YexaaLocalConstant {
  Ritu = {
    name_TE: ["వసంత", "గ్రీష్మ", "వర్షా", "శరద్", "హేమంత", "శిశిర"],
    name: ["Spring", "Summer", "Monsoon", "Autumn", "Pre-Winter", "Winter"],
  };

  Masa = {
    name_TE: [
      "చైత్ర",
      "వైశాఖ",
      "జ్యేష్ఠ",
      "ఆషాఢ",
      "శ్రావణ",
      "భాద్రపద",
      "ఆశ్వయుజ",
      "కార్తిక",
      "మార్గశిర",
      "పుష్య",
      "మాఘ",
      "ఫాల్గుణ",
    ],
    name: [
      "Chaitra",
      "Vishakam",
      "Jyesta",
      "Ashada",
      "Sravana",
      "Badhrapada",
      "Aswayuja",
      "Karthika",
      "Margasira",
      "Pusya",
      "Magha",
      "Phalguna",
    ],
  };

  Raasi = {
    name_TE: [
      "మేష",
      "వృషభ",
      "మిథున",
      "కర్కాటక",
      "సింహ",
      "కన్య",
      "తుల",
      "వృశ్చిక",
      "ధనుస్సు",
      "మకర",
      "కుంభ",
      "మీన",
    ],
    name: [
      "Aries",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpio",
      "Sagittarius",
      "Capricorn",
      "Aquarius",
      "Pisces",
    ],
  };

  Day = {
    name_TE: [
      "ఆదివారం",
      "సోమవారం",
      "మంగళవారం",
      "బుధవారం",
      "గురువారం",
      "శుక్రవారం",
      "శనివారం",
    ],
    name: [
      "sunday",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
    ],
  };

  Nakshatra = {
    name_TE: [
      "అశ్విని",
      "ద్విజ",
      "కృత్తిక",
      "రోహిణి",
      "మృగశిర",
      "ఆర్ద్ర",
      "పునర్వసు",
      "పుష్య",
      "ఆశ్లేష",
      "మఘ",
      "పూర్వఫల్గుణి",
      "ఉత్తరఫల్గుణి",
      "హస్త",
      "చిత్రా",
      "స్వాతి",
      "విశాఖ",
      "అనూరాధ",
      "జ్యేష్ఠ",
      "మూల",
      "పూర్వాషాఢ",
      "ఉత్తరాషాఢ",
      "శ్రవణ",
      "ధనిష్ఠ",
      "శతభిష",
      "పూర్వభాద్రపద",
      "ఉత్తరభాద్రపద",
      "రేవతి",
    ],
    name: [
      "ashwini",
      "bharani",
      "krithika",
      "rohini",
      "mrigashirsha",
      "ardra",
      "punarvasu",
      "pushya",
      "ashlesha",
      "makha",
      "purva_phalguni",
      "uttara_phalguni",
      "hasta",
      "chitra",
      "swati",
      "vishaka",
      "anuradha",
      "jyeshta",
      "moola",
      "purva_ashadha",
      "uttara_ashadha",
      "shravana",
      "dhanishta",
      "shatabhisha",
      "purva_bhadrapada",
      "uttara_bhadrapada",
      "revati",
    ],
  };

  Paksha = {
    name: ["Shukla", "Krishna"],
    name_TE: ["శుక్ల", "కృష్ణ"],
  };

  Tithi = {
    name_TE: [
      "ಪಾಡ್ಯ",
      "ಬಿದಿಗೆ",
      "ತದಿಗೆ",
      "ಚೌತಿ",
      "ಪಂಚಮಿ",
      "ಷಷ್ಠಿ",
      "ಸಪ್ತಮಿ",
      "ಅಷ್ಟಮಿ",
      "ನವಮಿ",
      "ದಶಮಿ",
      "ಏಕಾದಶಿ",
      "ದ್ವಾದಶಿ",
      "ತ್ರಯೋದಶಿ",
      "ಚತುರ್ದಶಿ",
      "ಹುಣ್ಣಿಮೆ",
      "ಪಾಡ್ಯ",
      "ಬಿದಿಗೆ",
      "ತದಿಗೆ",
      "ಚೌತಿ",
      "ಪಂಚಮಿ",
      "ಷಷ್ಠಿ",
      "ಸಪ್ತಮಿ",
      "ಅಷ್ಟಮಿ",
      "ನವಮಿ",
      "ದಶಮಿ",
      "ಏಕಾದಶಿ",
      "ದ್ವಾದಶಿ",
      "ತ್ರಯೋದಶಿ",
      "ಚತುರ್ದಶಿ",
      "ಅಮಾವಾಸ್ಯೆ",
    ],
    name: [
      "Padyami",
      "Vidiya",
      "Thadiya",
      "Chaviti",
      "Panchami",
      "Shasti",
      "Saptami",
      "Ashtami",
      "Navami",
      "Dasami",
      "Ekadasi",
      "Dvadasi",
      "Trayodasi",
      "Chaturdasi",
      "Pournami",
      "Padyami",
      "Vidiya",
      "Thadiya",
      "Chaviti",
      "Panchami",
      "Shasti",
      "Saptami",
      "Ashtami",
      "Navami",
      "Dasami",
      "Ekadasi",
      "Dvadasi",
      "Trayodasi",
      "Chaturdasi",
      "Amavasya",
    ],
  };

  Karna = {
    name: [
      "bawa",
      "balava",
      "kaulava",
      "taitula",
      "garaja",
      "vanija",
      "vishti",
      "sakuna",
      "chatushpada",
      "nagava",
      "kimstughana",
    ],
    name_TE: [
      "బవ",
      "బాలవ",
      "కౌలవ",
      "తైతిల",
      "గర",
      "వాణిజ్య",
      "విష్టి",
      "శకుని",
      "చతుష్పద",
      "నాగ",
      "కింస్తుఘ్న",
    ],
  };

  Yoga = {
    name: [
      "vishkambha",
      "prithi",
      "ayushman",
      "saubhagya",
      "sobhana",
      "atiganda",
      "sukarman",
      "dhrithi",
      "soola",
      "ganda",
      "vridhi",
      "dhruva",
      "vyaghata",
      "harshana",
      "vajra",
      "siddhi",
      "vyatipata",
      "variyan",
      "parigha",
      "siva",
      "siddha",
      "sadhya",
      "subha",
      "sukla",
      "bramha",
      "indra",
      "vaidhruthi",
    ],
    name_TE: [
      "విష్కంభ",
      "ప్రీతి",
      "ఆయుష్మాన్",
      "సౌభాగ్య",
      "శోభన",
      "అతిగండ",
      "సుకర్మ",
      "ధృతి",
      "శూల",
      "గండ",
      "వృద్ధి",
      "ధ్రువ",
      "వ్యాఘాత",
      "హర్షణ",
      "వజ్ర",
      "సిద్ధి",
      "వ్యతిపాత",
      "వరీయాన్",
      "పరిఘ",
      "శివ",
      "సిద్ధ",
      "సాధ్య",
      "శుభ",
      "శుక్ల",
      "బ్రహ్మ",
      "ఇంద్ర",
      "వైధృతి",
    ],
  };

  Trinity = {
    name: ["Brahma", "Vishnu", "Shiva"],
    name_TE: ["బ్రహ్మ", "విష్ణు", "శివ"],
  };

  Guna = {
    name: ["Rajas", "Tamas", "Satva"],
    name_TE: ["రాజస", "తమస", "సత్వ"],
  };

  Gana = {
    name: ["Devata", "Manushya", "Rakshasa"],
    name_TE: ["దేవత", "మనुष्य", "రాక్షస"],
  };

  Ayana = {
    name: ["Uttarayana", "Dakshinayana"],
    name_TE: ["ఉత్తరాయణం", "దక్షిణాయనం"],
  };
  DrikRitu = {
    name: ["Vasanta", "Grishma", "Varsha", "Sharad", "Hemanta", "Sishira"],
    name_TE: ["వసంత", "గ్రీష్మ", "వర్ష", "శరద్", "హేమంత", "శిశిర"],
  };
  TeluguYear = {
    name: [
      "Prabhava",
      "Vibhava",
      "Shukla",
      "Pramodyuta",
      "Prajotpatti",
      "Angirasa",
      "Shri Mukha",
      "Bhava",
      "Yuva",
      "Dhata",
      "Ishvara",
      "Bahudhanya",
      "Pramathi",
      "Vikrama",
      "Vrisha",
      "Chitrabhanu",
      "Svabhanu",
      "Tarana",
      "Parthiva",
      "Vyaya",
      "Sarvajittu",
      "Sarvadhari",
      "Virodhi",
      "Vikruti",
      "Khara",
      "Nandana",
      "Vijaya",
      "Jaya",
      "Manmatha",
      "Durmukhi",
      "Hevilambi",
      "Vilambi",
      "Vikari",
      "Sharvari",
      "Plava",
      "Shubhakrutu",
      "Shobhakrutu",
      "Krodhi",
      "Vishvavasu",
      "Parabhava",
      "Plavanga",
      "Kilaka",
      "Saumya",
      "Sadharana",
      "Virodhikrutu",
      "Paridhavi",
      "Pramadeecha",
      "Ananda",
      "Rakshasa",
      "Nala",
      "Pingala",
      "Kalayukti",
      "Siddharthi",
      "Raudri",
      "Durmati",
      "Dundubhi",
      "Rudhrodgari",
      "Raktakshi",
      "Krodhana",
      "Akshaya",
    ],
    name_TE: [
      "ప్రభవ",
      "విభవ",
      "శుక్ల",
      "ప్రమోద్యూత",
      "ప్రజోత్పత్తి",
      "అంగీరస",
      "శ్రీముఖ",
      "భవ",
      "యువ",
      "ధాత",
      "ఈశ్వర",
      "బహుధాన్య",
      "ప్రమాధి",
      "విక్రమ",
      "వృష",
      "చిత్రభాను",
      "స్వభాను",
      "తారణ",
      "పార్థివ",
      "వ్యయ",
      "సర్వజిత్తు",
      "సర్వధారి",
      "విరోధి",
      "వికృతి",
      "ఖర",
      "నందన",
      "విజయ",
      "జయ",
      "మన్మధ",
      "దుర్ముఖి",
      "హేవళంబి",
      "విళంబి",
      "వికారి",
      "శార్వరి",
      "ప్లవ",
      "శుభకృతు",
      "శోభకృతు",
      "క్రోధి",
      "విశ్వావసు",
      "పరాభవ",
      "ప్లవంగ",
      "కీలక",
      "సౌమ్య",
      "సాధారణ",
      "విరోధికృతు",
      "పరిధావి",
      "ప్రమాదీచ",
      "ఆనంద",
      "రాక్షస",
      "నల",
      "పింగళ",
      "కాళయుక్తి",
      "సిద్ధార్ది",
      "రౌద్రి",
      "దుర్మతి",
      "దుందుభి",
      "రుధిరోద్గారి",
      "రక్తాక్షి",
      "క్రోధన",
      "అక్షయ",
    ],
  };
}
